const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const progress=$("#progress");
addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max?scrollY/max*100:0}%`},{passive:true});
const menu=$("#menuBtn"),nav=document.querySelector("nav");
menu.onclick=()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)};
$$("nav a").forEach(a=>a.onclick=()=>nav.classList.remove("open"));
const theme=$("#themeBtn");
theme.onclick=()=>{document.documentElement.classList.toggle("light");theme.textContent=document.documentElement.classList.contains("light")?"☀":"☾"};
const sections=$$("main section[id]"),links=$$("nav a");
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+e.target.id))}),{rootMargin:"-40% 0px -50% 0px"});
sections.forEach(s=>io.observe(s));
const dialog=$("#caseDialog"),close=$("#dialogX"),dTitle=$("#dialogTitle"),dDesc=$("#dialogDesc"),dStack=$("#dialogStack"),dLink=$("#dialogLink"),dCat=$("#dialogCat");
$$(".project-card").forEach(card=>card.addEventListener("click",()=>{dTitle.textContent=card.dataset.title;dDesc.textContent=card.dataset.desc;dCat.textContent=card.querySelector(".project-label").textContent;dStack.innerHTML=card.dataset.stack.split(" · ").map(x=>`<span>${x}</span>`).join("");if(card.dataset.url&&card.dataset.url!=="#"){dLink.href=card.dataset.url;dLink.style.display="inline-flex"}else dLink.style.display="none";dialog.showModal()}));
close.onclick=()=>dialog.close();dialog.addEventListener("click",e=>{if(e.target===dialog)dialog.close()});
const form=$("#contactForm"),status=$("#formStatus"),submit=$("#submitBtn");
const googleFormURL="https://docs.google.com/forms/u/0/d/e/1FAIpQLSflRXZrRr_cCyGBdfQo2WTqbEYaGsQgOWpzLXNiG2UxE0mpfw/formResponse";
form.addEventListener("submit",async e=>{e.preventDefault();submit.disabled=true;submit.textContent="SENDING...";try{await fetch(googleFormURL,{method:"POST",body:new FormData(form),mode:"no-cors"});form.reset();status.textContent="MESSAGE SENT! ⚡"}catch{status.textContent="COULDN'T SEND — TRY GITHUB/LINKEDIN."}submit.disabled=false;submit.innerHTML="SEND IT! <span>➜</span>"});
$("#year").textContent=new Date().getFullYear();
